// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdeATQYX01ZRqKZu577u4OHqbTLGMTAM',
    appId: '1:948370526957:web:55de6d8b932e1a923132e4',
    messagingSenderId: '948370526957',
    projectId: 'homerex-3a1f9',
    authDomain: 'homerex-3a1f9.firebaseapp.com',
    storageBucket: 'homerex-3a1f9.appspot.com',
    measurementId: 'G-BPCRHVT6J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkFhnKKyPYlKpL2E40qCV0QiqO7Xx424',
    appId: '1:948370526957:android:720ad38bac9e2d593132e4',
    messagingSenderId: '948370526957',
    projectId: 'homerex-3a1f9',
    storageBucket: 'homerex-3a1f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtunkruu15XpiDLut3V-EMa-vlSF3MdQ4',
    appId: '1:948370526957:ios:f38eb6fbdcf918bc3132e4',
    messagingSenderId: '948370526957',
    projectId: 'homerex-3a1f9',
    storageBucket: 'homerex-3a1f9.appspot.com',
    iosClientId: '948370526957-60g7ehah2adkim58kfivpp0o83nbf78n.apps.googleusercontent.com',
    iosBundleId: 'com.example.homerex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtunkruu15XpiDLut3V-EMa-vlSF3MdQ4',
    appId: '1:948370526957:ios:d85e361c966ba3d43132e4',
    messagingSenderId: '948370526957',
    projectId: 'homerex-3a1f9',
    storageBucket: 'homerex-3a1f9.appspot.com',
    iosClientId: '948370526957-089gthf57g9427duincun8p9b4v4u5et.apps.googleusercontent.com',
    iosBundleId: 'com.example.homerex.RunnerTests',
  );
}
